### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by sarkiroka** [scottrogowski/code2flow#27] opened 2021-07-30 12:51 UTC
I found this lib in a blog and try to use with my project. I have lot of javascript files. When I use this lib, it process files (writes out to console) but always failed:
```
Traceback (most recent call last):
  File "/home/username/.local/bin/code2flow", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/engine.py", line 625, in main
    code2flow(
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/engine.py", line 515, in code2flow
    output_ext = output_file.rsplit('.', 1)[1] or ''
IndexError: list index out of range
```

My command is here: `code2flow --language js --output png $(pwd)`

Can you help me whit this issue?

**Comment by scottrogowski** [comment] 2021-07-30 13:55
Hi @sarkiroka 

The problem is that code2flow is looking for an extension on the output filename. To fix, instead of `--output png`, you need something like `--output filename.png`. 

I tweaked the source so that others don't stumble over it in the future but it's not enough of a change for a release yet.

Closing this issue. Feel free to open another if you have any more problems.

**Closed by scottrogowski** 2021-07-30 13:55 UTC

**Comment by sarkiroka** [comment] 2021-08-02 06:14
Thanks your quick answer.
I try to use full filename in output `code2flow --language 'js' --output output.png .` and `code2flow --language 'js' --output output.png $(pwd)` but there is no success:

`Traceback (most recent call last):
  File "/home/username/.local/bin/code2flow", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/engine.py", line 625, in main
    code2flow(
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/engine.py", line 522, in code2flow
    raise AssertionError(
AssertionError: Can't generate a flowchart image because neither `dot` nor `dot.exe` was found. Either install graphviz (see the README) or set your --output argument to a 'dot' filename like out.dot or out.gv.`

Okay, I installed graphviz but get another error message

`Traceback (most recent call last):
  File "/home/username/.local/bin/code2flow", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/engine.py", line 625, in main
    code2flow(
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/engine.py", line 531, in code2flow
    file_groups, all_nodes, edges = map_it(sources, language, no_trimming,
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/engine.py", line 306, in map_it
    language.assert_dependencies()
  File "/home/username/.local/lib/python3.8/site-packages/code2flow/javascript.py", line 241, in assert_dependencies
    assert is_installed('acorn'), "Acorn is required to parse javascript files " \
AssertionError: Acorn is required to parse javascript files but was not found on the path. Install it from npm and try again.
`

I don't know what do I wrong.

**Comment by scottrogowski** [comment] 2021-08-04 13:00
Follow the error :)

| AssertionError: Acorn is required to parse javascript files but was not found on the path. Install it from npm and try again.

So you need to do `npm install -g acorn`

**Comment by scottrogowski** [comment] 2021-08-04 13:04
Wrote a comment but realized I read yours too fast.

Acorn is required to parse javascript files with code2flow. There are various ways to install acorn but package managers like NPM are the most common.

It sounds like your setup is a bit complex if you're using Docker. I'm curious... what are you trying to do?
